### ISSUE TITLE
Jumbotron Image

### ISSUE THREAD

**Issue by RenaeCamp** [uidaholib/HJCCC_source#21]
@dcnb I tried to replace the jumbotron image with a new photo that I uploaded here: /objects/aacc-bowls4-resized.jpg by editing the config.yml file,  The image doesn't seem to be changing so I'm wondering if I did something wrong.

**Comment by evanwill** [comment]
The jumbotron wasn't pulling from that site variable, but was using `featured-image:` on `index.md`. 

It looks like Devin fixed that yesterday in 6e794e63ebe541eb197996ca3777431e53694ff9, so now it IS using `jumbotron-image:` in `_config.yml`. 

However, the new image doesn't work very well on larger screens--because of the way jumbtrons resize (the image is a background set to cover the whole area) it is just black with a tiny bit of the top of cups.

**Comment by RenaeCamp** [comment]
I re-sized the jumbotron image and I think it fits much better now.  I have one other image that I might try, but I think I'm pretty happy with the way this looks on the CDIL computers.

**Comment by evanwill** [comment]
that seems to work better, thanks!
