### ISSUE TITLE
Add attribution metadata to downloadable images

### ISSUE THREAD

**Issue by RenaeCamp** [uidaholib/HJCCC_source#30]
The Burke is fine with our downloadable images as long as we embed an attribution statement into the metadata.  I think this attribution can just be pulled from the Preferred Image Citation field, for example "Photo courtesy of the Burke Museum of Natural History and Culture, catalog nos. 45SN398B/2007/232 and 45SN398B/2007/279, US Air Force Collection, held in trust at the Burke Museum, Seattle."

@evanwill and @dcnb, I think we can probably also close out a few of the other open issues on this page, yes?  I've got a couple things I want to tweak on the About Page (I'll open another issue for those) but then I think we can call this done for a while.  Woo-hoo!

**Comment by RenaeCamp** [comment]
@evanwill and @dcnb I wanted to check and see if the attribution statement had been added to the downloadable images yet so that I can let the partners know the site is up and finalized.  Let me know if there is anything I can do to help (with my admittedly meger skill set...).  I'd like to start publicizing the site, but want to make sure we've met the Burke's requirements first.  Thanks!

**Comment by evanwill** [comment]
All the Burke images have IPTC:Source (which has a ~30 character limit) of "Burke Museum 45SN398B/2007" and XMP-dc:Source of "Photo courtesy of the Burke Museum of Natural History and Culture, catalog nos. 45SN398B/2007, US Air Force Collection, held in trust at the Burke Museum, Seattle." added now. Also, the image filename is the full catalog number. That seems good?

using exiftool: 

`exiftool -IPTC:Source="Burke Museum 45SN398B/2007" -XMP-dc:Source="Photo courtesy of the Burke Museum of Natural History and Culture, catalog nos. 45SN398B/2007, US Air Force Collection, held in trust at the Burke Museum, Seattle." *.jpg`

**Comment by evanwill** [comment]
wait, I am going to add one more tag--the problem is that Windows and most viewers don't recognize hardly any metadata tags--so you don't see the info unless you open in Photoshop or GIMP. I am going to add another that should be visible when you right click and look at image properties in Windows... (monday)

**Comment by evanwill** [comment]
@RenaeCamp Burke images have lots of embedded metadata now! 

Try downloading an image, right click > Properties > Details, now will display Title: "Historical Japanese Ceramic Comparative Collection", Copyright: "Photo courtesy of the Burke Museum of Natural History and Culture, catalog nos. 45SN398B/2007, US Air Force Collection, held in trust at the Burke Museum, Seattle."

**Comment by RenaeCamp** [comment]
@evanwill  Looks good except that I just realized the catalog number is missing the last part that identifies the artifact.  For example, 45SN398B/2007/228.1 or 45SN398B/2007/1466B (not 45SN398B/2007).  The full catalog numbers should be in the "prefered image citation" field of the object data table but, if you can't incorporate the whole number, you could just make the copyright read "Photo courtesy of the Burke Museum of Natural History and Culture, US Air Force Collection, held in trust at the Burke Museum, Seattle" for each artifact.

**Comment by evanwill** [comment]
All the Burke items are from one series, where 45SN398B seems to be the site number, and 2007 excavation year, followed by the item id. Since the file name is already the full identifier, it seemed helpful to general parts of the identifier, which I assume would point at some related grouping of objects in the holdings (I couldn't check since they don't make this part of the catalog public), so I assumed that 45SN398B/2007 would be helpful pointer to track down the source.

I can add the item numbers in some time this week, I just suspect that all this work is going to help 0 users (even if it really is a digital preservation best practice :wink: that we should build into some of our other collection workflows--so I guess it is a good exercise?).

**Comment by evanwill** [comment]
All the burke images now have full "catalog nos.", 
added with this command, which sort of makes me smile :smile: 

`for f in *.jpg; do A="${f#45SN398B-2007-}"; NAME="${A%_*.jpg}"; exiftool -Title="Historical Japanese Ceramic Comparative Collection" -Copyright="Photo courtesy of the Burke Museum of Natural History and Culture, catalog nos. 45SN398B/2007/${NAME%.jpg}, US Air Force Collection, held in trust at the Burke Museum, Seattle." -XMP-dc:Source="Photo courtesy of the Burke Museum of Natural History and Culture, catalog nos. 45SN398B/2007/${NAME%.jpg}, US Air Force Collection, held in trust at the Burke Museum, Seattle." "$f"; done`

And the AACC items have some embedded metadata now too, 

`exiftool -Title="Historical Japanese Ceramic Comparative Collection" -Copyright="Photo courtesy of the Asian American Comparative Collection, University of Idaho." -XMP-dc:Source="Photo courtesy of the Asian American Comparative Collection, University of Idaho." *.jpg`

**Comment by RenaeCamp** [comment]
Awesome!  That's an appropriate way to wrap things up!
